### ISSUE TITLE
Incorrect login credentials

### ISSUE THREAD

**Issue by vhespanha** [xou816/spot#726]
**Describe the bug**
I cant authenticate to my Spotify account using the Spot client, no matter the account or how many times i reset the password, i get the "Incorrect login credentials". Same credentials work on other devices/clients.

**To Reproduce**
1. Install Spot (Flatpak)
2. Type credentials
3. Click "Log in"

**Expected behavior**
Sign into my account

**Screenshots**
![image](https://github.com/user-attachments/assets/fdc692ff-fb39-494a-aa0e-45bf4b8806e0)

**General information:**
 - Distribution: Arch Linux
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.4.1
 - Device used [e. g. desktop, phone...]: desktop

**Additional context**
I found another guy on the Gnome Software review section saying he had the same problem, I installed Spot on this same machine back in June and used it normally, after reinstalling the system, i get this error.

**Comment by vhespanha** [comment]
Issue persists also when built from source.

**Comment by joaocandre** [comment]
Facing this issue as well on Arch (AUR installation). I'm using a Family account, wonder if it may be related to that?

**Comment by JJ-Atkinson** [comment]
I'm using a personal account and can't login either. Wonder if spotify did something here? Using nixos stable version

**Comment by vhespanha** [comment]
I'm on family too, but seems like it's unrelated.
The other guy with the same problem commented it back in may, i successfully logged in back in june, so i also don't think this stems from a change on Spotify's API either.

**Comment by Psikyd** [comment]
same issue here (personnal account) 
I'm on Nobara 40 and using the flatpak version
![spot_login_issue](https://github.com/user-attachments/assets/91567142-bc00-45bb-9c4a-f9434db8c147)

**Comment by mobergmann** [comment]
I am also experiencing the same issue on NixOS using the nixpkgs version.

**Comment by Dvaderfun** [comment]
Fedora 40, Flatpak, Student Subscription. Same problem

**Comment by vhespanha** [comment]
Definitely not a subscription issue. I'll review the Spotify API documentation to check for any recent changes.

Also, for me, the error appears almost instantly. It doesn't seem like the server is even processing the credentials. This might indicate that the client is poorly handling the response from a possibly malformed request.

**Comment by JJ-Atkinson** [comment]
https://github.com/librespot-org/librespot/issues/1308

Looks like it's not spots fault.

**Comment by Psikyd** [comment]
Yes it has been resolved today for me !

**Comment by mobergmann** [comment]
I can also login again

**Comment by JJ-Atkinson** [comment]
Perusing the librespot issue, it appears that spot would need to be retrofitted with an oauth flow. Might be worth an issue for any repo owners.

**Comment by SpamixOfficial** [comment]
This also affects me at the moment. Might be worth mentioning that I am using the flatpak build of Spot since there's no native package for Fedora

This issue is worth re-opening in my opinion since the issue is still present for a number of people (including me)

**Comment by vhespanha** [comment]
@SpamixOfficial, re-opened it.
I never got to investigate it, but, since it's still affecting people I'll take a look and see if I can find something useful.

**Comment by SpamixOfficial** [comment]
> @SpamixOfficial, re-opened it.
> 
> I never got to investigate it, but, since it's still affecting people I'll take a look and see if I can find something useful.

I'll also take a look once I get home. Thanks for reopening!

**Comment by G-M0N3Y-2503** [comment]
I was actually working on [OAuth for my Spotify client in Rust](https://github.com/G-M0N3Y-2503/spotifyrs/blob/1ab80483c9af997d5e04d0007e49ff0dc0c0e17d/spotify-api/src/authorisation.rs) before I found this app and gave up on it.  
In fact, OAuth for the API was the only thing I finished implementing.
I just made it public and would appreciate attribution if you found it helpful.

**Comment by Arche151** [comment]
Same issue. Can't log in :(

**Comment by QuarTheDev** [comment]
Running the spot flatpak on Fedora Workstation 40. I'm unsure if this is relevant or not, but I signed up with a Google account and thus my account does not have a password (try going into settings > account > email and password field is greyed out). I've tried my username and email to no luck -- and since my account doesn't have a password, I tried my Google password as well, but to no luck. Perhaps it's best the login form be replaced with either an OAuth flow like @JJ-Atkinson mentioned, or a way to login via pasting an <a href="https://developer.spotify.com/documentation/web-api/concepts/access-token">access token</a>
<img src="https://github.com/user-attachments/assets/b87bf5f5-0a2c-4d30-815a-7354c40a3bbe" width="350px">

**Comment by QuarTheDev** [comment]
Running the spot flatpak on Fedora Workstation 40. I'm unsure if this is relevant or not, but I signed up with a Google account and thus my account does not have a password (try going into settings > account > email and password field is greyed out). I've tried my username and email to no luck -- and since my account doesn't have a password, I tried my Google password as well, but to no luck. Perhaps it's best the login form be replaced with either an OAuth flow like @JJ-Atkinson mentioned, or a way to login via pasting an <a href="https://developer.spotify.com/documentation/web-api/concepts/access-token">access token</a>.

**Comment by kiiatto** [comment]
won't let me in either
Arch Linux, latest version on Flathub
premium personal plan

**Comment by vhespanha** [comment]
Hey guys, I don't think I can find a way to fix this at all, since I'm having the same issue on Spotifyd, this is probably an issue with the Spotify API itself, there could be a workaround but I haven't been able to get it to work.

I'll be closing it since it's not anything that the Spot app itself should fix, if there's any solution, it would have to be merged to Librespot and Spotifyd.

**Comment by SpamixOfficial** [comment]
Okay @vhespanha Thanks for looking into this!

Have an amazing week :-)

**Comment by vhespanha** [comment]
The librespot dev branch already has a fix for this, by implementing OAuth, unfortunately, Spot already uses the latest librespot release, which came out two years ago, and i dont really think it would be a good idea to use the dev branch of a dependency in a release of the app, but **theoretically** one could build Spot using librespot's dev branch themselfs and it should work, I might try this later.

**Comment by adityamwagh** [comment]
Around when do you expect this issue to get resolved? Can you provide some estimated time so that I can check again at that time?

**Comment by kiiatto** [comment]
> The librespot dev branch already has a fix for this, by implementing OAuth, unfortunately, Spot already uses the latest librespot release, which came out two years ago, and i dont really think it would be a good idea to use the dev branch of a dependency in a release of the app, but **theoretically** one could build Spot using librespot's dev branch themselfs and it should work, I might try this later.

maybe a dev version of spot (e.g. spot-dev)?

**Comment by SpamixOfficial** [comment]
> > The librespot dev branch already has a fix for this, by implementing OAuth, unfortunately, Spot already uses the latest librespot release, which came out two years ago, and i dont really think it would be a good idea to use the dev branch of a dependency in a release of the app, but **theoretically** one could build Spot using librespot's dev branch themselfs and it should work, I might try this later.
> 
> 
> 
> maybe a dev version of spot (e.g. spot-dev)?

Yeah but that could also introduce a ton of instability since it's a dev branch if librespot

**Comment by kiiatto** [comment]
> > > The librespot dev branch already has a fix for this, by implementing OAuth, unfortunately, Spot already uses the latest librespot release, which came out two years ago, and i dont really think it would be a good idea to use the dev branch of a dependency in a release of the app, but **theoretically** one could build Spot using librespot's dev branch themselfs and it should work, I might try this later.
> > 
> > 
> > maybe a dev version of spot (e.g. spot-dev)?
> 
> Yeah but that could also introduce a ton of instability since it's a dev branch if librespot

dev versions are almost expected to be instable, it'll be _fine_ right?

**Comment by SpamixOfficial** [comment]
> > > > The librespot dev branch already has a fix for this, by implementing OAuth, unfortunately, Spot already uses the latest librespot release, which came out two years ago, and i dont really think it would be a good idea to use the dev branch of a dependency in a release of the app, but **theoretically** one could build Spot using librespot's dev branch themselfs and it should work, I might try this later.
> 
> > > 
> 
> > > 
> 
> > > maybe a dev version of spot (e.g. spot-dev)?
> 
> > 
> 
> > Yeah but that could also introduce a ton of instability since it's a dev branch if librespot
> 
> 
> 
> dev versions are almost expected to be instable, it'll be _fine_ right?

Yes they are expected to be unstable but the case might be that a ton of functions spot uses has been deprecated, removed or how it is used has changed completely. Just speculating right now but there might be more reasons they haven't upgraded than the fact that it's unstable :(

**Comment by vhespanha** [comment]
Awesome, thanks a lot @stevenleadbeater, life-saver.
